# Generated by Django 4.2 on 2023-04-26 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_tree_up', '0003_remove_menupoint_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menupoint',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_menu_points', to='menu_tree_up.menu'),
        ),
    ]
