# Generated by Django 4.2 on 2023-04-26 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_tree_up', '0004_menupoint_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menupoint',
            name='url',
            field=models.CharField(max_length=100, validators=[django.core.validators.URLValidator()], verbose_name='URL'),
        ),
    ]
